### ISSUE TITLE
Unable to add LocalDate format in 1.2.1

### ISSUE THREAD

**Issue by acanby** [grails-plugins/grails-java8#7] opened 2017-11-17 00:44 UTC
I'm hoping this is my misunderstanding, but I'm unable to define any custom date formats using Grails 3.3.1 and grails-java8:1.2.1.

Previously, in Grails 3.2.11 I have the following:
```yml
grails:    
    databinding:
        dateFormats:
          - yyyy-MM-dd HH:mm:ss.S
          - yyyy-MM-dd'T'HH:mm:ss'Z'
          - yyyy-MM-dd HH:mm:ss.S z
          - yyyy-MM-dd'T'HH:mm:ss.SSSX
          - yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
          - yyyy-MM-dd
```

This allows me to use `java.time.LocalDate` in Command objects.

Doing the same using 3.1.1 & 1.2.1 I am unable to use anything other than the defaults. Debugging the issue it seems to be here (Java8GrailsPlugin.groovy - simplified):

```groovy
 Field formats
 try {
   formats = DataBindingGrailsPlugin.getDeclaredField('DEFAULT_DATE_FORMATS')
 } catch (NoSuchFieldException e) {
   formats = Settings.getDeclaredField('DATE_FORMATS')
 }
 String dateFormatProperty = formats.get(null)

 List dateFormats = config.getProperty(dateFormatProperty, List, DataBindingGrailsPlugin.DEFAULT_DATE_FORMATS)
 
 jsr310DataBinding(Jsr310ConvertersConfiguration) {
   formatStrings = dateFormats
 }
```

I can't see an instance whereby the exception is thrown, unless the grails-plugin-datatbinding changes, so there is no way that the formats will use what is entered in `grails.databinding.dateFormats`

I notice that in #5 there is a change to instead use `DataBindingGrailsPlugin.getDeclaredField('DATE_FORMATS')`, This doesn't work in 3.3+, however `Settings.getDeclaredField('DATE_FORMATS')` does allow my above YAML to work. 

I'd like to propose for discussion the following (all can be implemented separately):

1. Reverse the formats ordering, to check for a user specified `DATE_FORMATS` before falling back to the `DEFAULT_DATE_FORMATS`:

```groovy
 try {
   formats = Settings.getDeclaredField('DATE_FORMATS')
 } catch (NoSuchFieldException e) {
   formats = DataBindingGrailsPlugin.getDeclaredField('DEFAULT_DATE_FORMATS')
 }
```

2. Introduce a `DEFAULT_JAVA8_DATE_FORMATS` property into the plugin.
   * Without this, you can't use the plugin out of the box (if you want to use `java.time.LocalDate` etc).
   * If/when introduced, change the date format loading to use the new property instead of the core java formats.

**Comment by jameskleeh** [comment] 2017-11-19 04:59
> I can't see an instance whereby the exception is thrown

The data binding grails plugin had that field removed for Grails 3.3: https://github.com/grails/grails-core/commit/63a9c6eb48e886a6f4123df6f553c8816eb84b97#diff-bb7355cca99b82a457a9a6d7ea16f671

> Reverse the formats ordering

How would that change anything?

> Introduce a DEFAULT_JAVA8_DATE_FORMATS property into the plugin

What would be the purpose of it?

**Comment by jameskleeh** [comment] 2017-11-19 05:02
Upload an example project that isn't working as you'd expect and I can look at it

**Comment by acanby** [comment] 2017-11-19 05:33
Hey @jameskleeh - sorry on mobile at the moment, I’ll update this comment when at the computer. 

Essentially my thoughts stemmed from https://github.com/acanby/grails-controller-localdate-test, which tries to use a LocalDate in a controller as a param.

Thanks for looking into this.

Cheers,
Andrew

**Comment by jameskleeh** [comment] 2017-11-21 01:44
@acanby I don't think that has anything to do with this issue, I'm not even sure what the issue is

**Comment by acanby** [comment] 2017-11-21 02:21
Hi @jameskleeh sorry about the delay. I think I've overloaded this issue a bit much and it's muddying what the root cause is - my apologies.

Essentially, using this app: https://github.com/acanby/grails-controller-localdate-test 

and calling 

```sh
curl -X GET 'http://localhost:8080/command/birthdays?birthday=2017-01-01'
```

I am unable to use my defined format (see here: https://github.com/acanby/grails-controller-localdate-test/blob/master/grails-app/conf/application.yml#L67-L74) for LocalDate.

The points of discussion I'll raise separately when I have an opportunity to articulate them more effectively.

Thanks again for your help

**Comment by jameskleeh** [comment] 2017-11-21 02:31
Using 1.2.2.BUILD-SNAPSHOT fixes the issue. Duplicate of #5

**Closed as completed by jameskleeh** 2017-11-21 02:31 UTC
Labels: duplicate

**Comment by acanby** [comment] 2017-11-22 10:03
Thanks @jameskleeh. I'll admit to being thrown by the title of #5 suggesting 3.3 wasn't affected.

Noticed 1.2.2 released - cheers 👍
